languageCode = "en"
languageName = "English"
weight = 1
title = "Johan Röjås"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
description = " "
dateFormat = "2 January 2006"

  [params.author]
  name = "Red Blowfish"
  image = "img/avatar.png"
  headline = "This is my website with my links"
  bio = "A little bit about you"

    [[params.author.links]]
    email = "johan.rojas@branddesign.se"

    [[params.author.links]]
    github = "https://github.com/brandwegg"

    [[params.author.links]]
    linkedin = "https:/linkedin.com/in/johan-röjås"

["params.author"]
name = "Johan Röjås"
headline = "Game Programmer"
image = "profile_picture.png"
bio = "I'm a student at The Game Assembly graduating in summer 2026 and looking for internship opportinities. Reach me at: johan.rojas@branddesign.se"
