languageCode = "en"
languageName = "English"
weight = 1
title = "Johan Röjås"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
description = "My awesome website"
dateFormat = "2 January 2006"

  [params.author]
  name = "Red Blowfish"
  image = "img/avatar.png"
  headline = "This is my website with my links"
  bio = "A little bit about you"

    [[params.author.links]]
    email = "johan.rojas@branddesign.se"

    [[params.author.links]]
    github = "https://github.com/brandwegg"

    [[params.author.links]]
    linkedin = "https:/linkedin.com/in/johan-röjås"

["params.author"]
name = "Johan Röjås"
headline = "Game Programmer"
image = "profile_picture.png"
bio = "I am part of The Game Assembly’s internship program. As per the agreement between the Games Industry and The Game Assembly, neither student nor company may be in contact with one another regarding internships before April 15th. Any internship offers can be made on April 27th, at the earliest."
